openapi: 3.0.0
info:
  title: CLiQQ Openpoints Integration API 
  version: 1.0.0
  description: |-
    This API specification is meant to be used by the Openpoints System.
servers:
  - url: https://op-link-sbx.cliqq.net
    description: sandbox 
  - url: https://op-link.cliqq.net
    description: production
tags:
  - name: account
    description: Everything about an account
paths:
  /account/binding:
    post:
      tags:
        - account
      summary: Request binding of openpoints member id to a new cliqq member account
      description: |-
        To be called when the user taps “Bind CLiQQ Card” for and agrees to T&C. A new CLiQQ
        member is created, along with a newly created loyalty account using a new account 
        number prefix
      operationId: bindAccount
      security:
        - authorizationHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBinding'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBindingResult'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestBody'
        '401':
          description: Unauthorized Request
        '403':
          description: Invalid request signature
  /account/balanceInquiry:
    post:
      tags:
        - account
      summary: Request cliqq points balance
      description: |-
        To be called when the user views OP’s CLiQQ screen
      operationId: getAccountBalance
      security:
        - authorizationHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBalance'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBalanceResult'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestBody'
        '401':
          description: Unauthorized Request
        '403':
          description: Invalid request signature
  /account/conversion:
    post:
      tags:
        - account
      summary: Request conversion of cliqq points to openpoints
      description: |-
        To be called when the user converts their CLiQQ points to OP points
      operationId: convertPoints
      security:
        - authorizationHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountConversion'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConversionResult'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestBody'
        '401':
          description: Unauthorized Request
        '403':
          description: Invalid request signature
  /account/unbinding:
    post:
      tags:
        - account
      summary: Request account unbinding
      description: |-
        To be called when the user unlinks their CLiQQ account from their OP account
      operationId: unbindAccount
      security:
        - authorizationHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountUnbinding'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountUnbindingResult'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestBody'
        '401':
          description: Unauthorized Request
        '403':
          description: Invalid request signature
components:
  securitySchemes:
    authorizationHeader:
      type: apiKey
      name: Auhtorization
      in: header
  schemas:
    AccountBinding:
      type: object
      properties:
        requestId:
          description: unique request identifier, ksuid or uuid
          type: string
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        requestTime:
          description: timestamp
          type: string
          format: date-time
        openpointsId:
          description: identifier of the openpoints member
          type: string
          example: "2ZTcfhWKbgobnQNLBKiWWwcvUI6"
        sig:
          description: |-
            request signature produced by the following psuedo code:
            
            requestHash = sha256(concatenate(requestId,requestTime,openpointsId)
            
            sig = generateRSASignature(requestHash, rsaPrivateKey)
          type: string
          example: "2ZTcmShbPggCgpV0ynD8elT3qAZ2ZTcmSQPvIntyCXXO8OJIQjf4SN2ZTcmW5dtul6XonwBid24K6jJu12ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXWkX44JA4eFecLS34fKAlg"
    AccountBindingResult:
      type: object
      properties:
        requestId:
          type: string
          description: requestId from the request body
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        returnCode:
          type: string
          description: returnCode
          example: "200"
        returnMessage:
          type: string
          description: human readable message
          example: "Binding created successfully"
        cliqqId:
          type: string 
          description: cliqq member id bound to the openpoints id provided in the request body
          example: "2ZTcmX5iHITG5giMlHOpetX4zJ7"
        cliqqBarcode:
          type: string
          description: cliqq member barcode data used for earning cliqq points
          example: "9902000786865"
        processTime:
          description: timestamp
          type: string
          format: date-time
    AccountBalance:
      type: object
      properties:
        requestId:
          description: unique request identifier, ksuid or uuid
          type: string
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        requestTime:
          description: timestamp
          type: string
          format: date-time
        cliqqBarcode:
          type: string
          description: cliqq member barcode data used for earning cliqq points
          example: "9902000786865"
        sig:
          description: |-
            request signature produced by the following psuedo code:
            
            requestHash = sha256(concatenate(requestId,requestTime,cliqqBarcode)
            
            sig = generateRSASignature(requestHash, rsaPrivateKey)
          type: string
          example: "2ZTcmShbPggCgpV0ynD8elT3qAZ2ZTcmSQPvIntyCXXO8OJIQjf4SN2ZTcmW5dtul6XonwBid24K6jJu12ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXWkX44JA4eFecLS34fKAlg"
    AccountBalanceResult:
      type: object
      properties:
        requestId:
          type: string
          description: requestId from the request body
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        returnCode:
          type: string
          description: returnCode
          example: "200"
        returnMessage:
          type: string
          description: human readable message
          example: "Balance Inquiry successfully processed"
        cliqqPoints:
          type: string
          description: cliqq member points earned
          example: "99.08"
        processTime:
          description: timestamp
          type: string
          format: date-time
          
    AccountConversion:
      type: object
      properties:
        requestId:
          description: unique request identifier, ksuid or uuid
          type: string
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        requestTime:
          description: timestamp
          type: string
          format: date-time
        cliqqBarcode:
          type: string
          description: cliqq member barcode data used for earning cliqq points
          example: "9902000786865"
        deductCliqqPoints:
          type: string
          description: Points to deduct from the member balance
          example: "30.00"
        creditOpenPoints:
          type: string
          description: Points that will be credited to the openpoints member account
          example: "10.00"
        sig:
          description: |-
            request signature produced by the following psuedo code:
            
            requestHash = sha256(concatenate(requestId,requestTime,cliqqBarcode,deductCliqqPoints,creditOpenPoints)
            
            sig = generateRSASignature(requestHash, rsaPrivateKey)
          type: string
          example: "2ZTcmShbPggCgpV0ynD8elT3qAZ2ZTcmSQPvIntyCXXO8OJIQjf4SN2ZTcmW5dtul6XonwBid24K6jJu12ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXWkX44JA4eFecLS34fKAlg"
    AccountConversionResult:
      type: object
      properties:
        requestId:
          type: string
          description: requestId from the request body
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        returnCode:
          type: string
          description: returnCode
          example: "200"
        returnMessage:
          type: string
          description: human readable message
          example: "CLiQQ Point conversion successfully processed"
        deductCliqqPoints:
          type: string
          description: Points to deduct from the member balance
          example: "30.00"
        creditOpenPoints:
          type: string
          description: Points that will be credited to the openpoints member account
          example: "10.00"
        processTime:
          description: timestamp
          type: string
          format: date-time
          
    AccountUnbinding:
      type: object
      properties:
        requestId:
          description: unique request identifier, ksuid or uuid
          type: string
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        requestTime:
          description: timestamp
          type: string
          format: date-time
        openpointsId:
          description: identifier of the openpoints member
          type: string
          example: "2ZTcfhWKbgobnQNLBKiWWwcvUI6"
        sig:
          description: |-
            request signature produced by the following psuedo code:
            
            requestHash = sha256(concatenate(requestId,requestTime,cliqqBarcode,deductCliqqPoints,creditOpenPoints)
            
            sig = generateRSASignature(requestHash, rsaPrivateKey)
          type: string
          example: "2ZTcmShbPggCgpV0ynD8elT3qAZ2ZTcmSQPvIntyCXXO8OJIQjf4SN2ZTcmW5dtul6XonwBid24K6jJu12ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXsLsQD9gtqegprXlAeyX6v2ZTcmXWkX44JA4eFecLS34fKAlg"
    AccountUnbindingResult:
      type: object
      properties:
        requestId:
          type: string
          description: requestId from the request body
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        returnCode:
          type: string
          description: returnCode
          example: "200"
        returnMessage:
          type: string
          description: human readable message
          example: "Binding removed successfully"
        processTime:
          description: timestamp
          type: string
          format: date-time
    
    InvalidRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: requestId from the request body
          example: "2ZTcYqW6jGaTH3o2B0Rh8wPJmoG"
        returnCode:
          type: string
          description: returnCode
          example: "400"
        returnMessage:
          type: string
          description: human readable message
          example: "Invalid Request Body"
        processTime:
          description: timestamp
          type: string
          format: date-time